//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 06:45:19 PM EST 
//


package org.uvm.wilkie.nlpminer.xgmml.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.uvm.wilkie.nlpminer.xgmml.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Node_QNAME = new QName("http://www.cs.rpi.edu/XGMML", "node");
    private final static QName _Graph_QNAME = new QName("http://www.cs.rpi.edu/XGMML", "graph");
    private final static QName _Edge_QNAME = new QName("http://www.cs.rpi.edu/XGMML", "edge");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.uvm.wilkie.nlpminer.xgmml.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Center }
     * 
     */
    public Center createCenter() {
        return new Center();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link GraphicNode }
     * 
     */
    public GraphicNode createGraphicNode() {
        return new GraphicNode();
    }

    /**
     * Create an instance of {@link GraphicEdge }
     * 
     */
    public GraphicEdge createGraphicEdge() {
        return new GraphicEdge();
    }

    /**
     * Create an instance of {@link GraphicGraph }
     * 
     */
    public GraphicGraph createGraphicGraph() {
        return new GraphicGraph();
    }

    /**
     * Create an instance of {@link Att }
     * 
     */
    public Att createAtt() {
        return new Att();
    }

    /**
     * Create an instance of {@link Graphics }
     * 
     */
    public Graphics createGraphics() {
        return new Graphics();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link SimpleGraph }
     * 
     */
    public SimpleGraph createSimpleGraph() {
        return new SimpleGraph();
    }

    /**
     * Create an instance of {@link SimpleNode }
     * 
     */
    public SimpleNode createSimpleNode() {
        return new SimpleNode();
    }

    /**
     * Create an instance of {@link SimpleEdge }
     * 
     */
    public SimpleEdge createSimpleEdge() {
        return new SimpleEdge();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphicNode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cs.rpi.edu/XGMML", name = "node")
    public JAXBElement<GraphicNode> createNode(GraphicNode value) {
        return new JAXBElement<GraphicNode>(_Node_QNAME, GraphicNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphicGraph }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cs.rpi.edu/XGMML", name = "graph")
    public JAXBElement<GraphicGraph> createGraph(GraphicGraph value) {
        return new JAXBElement<GraphicGraph>(_Graph_QNAME, GraphicGraph.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphicEdge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cs.rpi.edu/XGMML", name = "edge")
    public JAXBElement<GraphicEdge> createEdge(GraphicEdge value) {
        return new JAXBElement<GraphicEdge>(_Edge_QNAME, GraphicEdge.class, null, value);
    }

}
